name: KillPlayers4Money
main: kenygamer\KillMoney\Main
version: 2.0.0-B1
api:
 - 3.0.0-ALPHA9
 - 3.0.0-ALPHA10

author: VMPE Development Team
website: Not showing.

commands:
 killmoney:
  description: Prints out information about this KillMoney installation.
  usage: /killmoney
  
permissions:
 killmoney.command:
  default: true
 killmoney.killer.receive.money:
  default: true
 killmoney.victim.lose.money:
  default: true
