name: KillMoney
main: kenygamer\KillMoney\Main
version: 1.1.3
api:
 - 3.0.0-ALPHA7
 - 3.0.0-ALPHA8

author: kenygamer
website: https://github.com/kenygamer/pmmp-plugins/blob/master/KillMoney

commands:
 killmoney:
  description: Prints out information about this KillMoney installation.
  usage: /killmoney
  
permissions:
 killmoney.command:
  default: true
 killmoney.killer.receive.money:
  default: true
 killmoney.victim.lose.money:
  default: true
